### ISSUE TITLE
Exception when certificate is expired

### ISSUE THREAD

**Issue by 8h2a** [stefan2904/collectd-tls-expiry-monitor#1]
https://github.com/stefan2904/collectd-tls-expiry-monitor/blob/2268e7c966308640121afb0ac17ab21c39929b39/tls_cert_monitor.py#L57
This line throws an exception when the certificate is expired.
This should probably be handled in a more graceful manner.

**Comment by stefan2904** [comment]
Hi, thank for reporting.

Would it help to catch the exception and return "0 days left" in that case, 
or do you think a negative value (days since expiry) would make sense?

I prefer the first option.

**Comment by 8h2a** [comment]
> Would it help to catch the exception and return "0 days left" in that case,

This is exactly what I ended up doing for my local copy of this script.

**Comment by stefan2904** [comment]
Happy to merge a PR. ;-)

**Comment by stefan2904** [comment]
@8h2a not sure if still relevant for you, but I think the change in 2dee5ed5fb14158932c21d82aa4bfffe352c6c31 should do it.
(I also added a test for this in aa8d94e919ee2c0f91a6ba4e1631bbe95caa98e2)
